name: Github Actions

on:
  release:
    types: [ released ]

jobs:
  Maven-Publish:
    name: Publish to MavenCentral
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Publish to MavenCentral
        run: ./gradlew publishKotlinPublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SDK_RELEASE_VERSION: ${{ github.event.release.tag_name }}